# Generated by Django 4.2.7 on 2023-12-06 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('phone1', models.CharField(max_length=255, null=True)),
                ('phone2', models.CharField(max_length=255, null=True)),
                ('educational_qualification', models.CharField(choices=[('+2', '+2'), ('Diploma', 'Diploma'), ('UG', 'UG'), ('PG', 'PG'), ('Ph.D', 'Ph.D')], max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('qualified', models.BooleanField(null=True)),
                ('papers_to_pass', models.IntegerField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True)),
                ('placement_preferred', models.BooleanField(null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.batch')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
