# Generated by Django 4.2.7 on 2023-12-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_student_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educational_qualification',
            field=models.CharField(choices=[('+2', '+2'), ('Diploma', 'Diploma'), ('BA ', 'BA'), ('BSc', 'BSc'), ('BCom', 'BCom'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Tech', 'B.Tech'), ('B.Ed', 'B.Ed'), ('BFA', 'BFA'), ('MA', 'MA'), ('MSc', 'MSc'), ('Mcom', 'Mcom'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('M.Tech', 'M.Tech'), ('M.Ed', 'M.Ed'), ('MFA', 'MFA'), ('Ph.D', 'Ph.D')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='work_experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
